spring:
  redis:
    host: localhost
    port: 6379
    password: 1234
    lettuce:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8  #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
    shutdown-timeout: 30000 #连接超时时间（毫秒）
    database: 0